### PR TITLE
PE-0.5.1-mobile-html5

### PR DESCRIPTION
**Pull request by Pasak1094**

### CODE REVIEW

**Comment by UNSTOP4BLE** [comment]
What is this

**Comment by Pasak1094** [comment]
This is me trying to create a custom menu

**Comment by UNSTOP4BLE** [comment]
Why make a pull request tho

**Comment by UNSTOP4BLE** [comment]
Just make a fork and upload the file to that github

**Comment by Pasak1094** [comment]
Thanks

**Pull request closed without merging**
